{{- if not .Values.existingConfigMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vector.fullname" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
data:
  {{- if .Values.customConfig }}
  vector.yaml: |
{{ tpl (toYaml .Values.customConfig) . | indent 4 }}
  {{- else if or (eq .Values.role "Aggregator") (eq .Values.role "Stateless-Aggregator") }}
  aggregator.yaml: |
{{ tpl (toYaml .Values.aggregatorConfig) . | indent 4 }}
  {{- else if (eq .Values.role "Agent") }}
  agent.yaml: |
{{ tpl (toYaml .Values.agentConfig) . | indent 4 }}
  {{- end }}
{{- end }}
